setwd("C:/Users/ester/OneDrive/Documents/cuentosgrimm")
dir.create("datos")
dir.create("datos/cuentos")

Blancanieve_y_rojarosa <- readLines("datos/cuentos/Blancanieve_y_rojarosa.txt", encoding = "UTF-8")
El_hombre_de_la_piel_de_oso <- readLines("datos/cuentos/El_hombre_de_la_piel_de_oso.txt", encoding = "UTF-8")
El_joven_gigante <- readLines("datos/cuentos/El_joven_gigante.txt", encoding = "UTF-8")
El_judio_en_las_espinas <- readLines("datos/cuentos/El_judio_en_las_espinas.txt", encoding = "UTF-8")
La_madre_vieja <- readLines("datos/cuentos/La_madre_vieja.txt", encoding = "UTF-8")
Juan_el_fiel <- readLines("datos/cuentos/Juan_el_fiel.txt", encoding = "UTF-8")
Juan_en_la_prosperidad <- readLines("datos/cuentos/Juan_en_la_prosperidad.txt", encoding = "UTF-8")
La_carga_ligera <- readLines("datos/cuentos/La_carga_ligera.txt", encoding = "UTF-8")
La_reina_de_las_abejas <- readLines("datos/cuentos/La_reina_de_las_abejas.txt", encoding = "UTF-8")
Las_tres_hilanderas <- readLines("datos/cuentos/Las_tres_hilanderas.txt", encoding = "UTF-8")
Los_doce_cazadores <- readLines("datos/cuentos/Los_doce_cazadores.txt", encoding = "UTF-8")
Los_musicos_de_Brema <- readLines("datos/cuentos/Los_musicos_de_Brema.txt", encoding = "UTF-8")
Los_tres_herederos_afortunados <- readLines("datos/cuentos/Los_tres_herederos_afortunados.txt", encoding = "UTF-8")
Rosa_con_espinas <- readLines("datos/cuentos/Rosa_con_espinas.txt", encoding = "UTF-8")
Ruiponche <- readLines("datos/cuentos/Ruiponche.txt", encoding = "UTF-8")

cuentos <- c(Blancanieve_y_rojarosa, El_hombre_de_la_piel_de_oso, El_joven_gigante, El_judio_en_las_espinas, Juan_el_fiel, Juan_en_la_prosperidad, La_carga_ligera, La_madre_vieja, La_reina_de_las_abejas, Las_tres_hilanderas, Los_doce_cazadores, Los_musicos_de_Brema, Los_tres_herederos_afortunados, Rosa_con_espinas, Ruiponche)
dir.create("codigo")
